# Experiments

### Setup

In [1]:
# Or you can use a .env file
from dotenv import load_dotenv
load_dotenv()

True

Here is the RAG Application that we've been working with throughout this course

In [2]:
import os
import nest_asyncio
from typing import List
from dotenv import load_dotenv
from openai import OpenAI
from langsmith import traceable
from app import get_vector_db_retriever

load_dotenv()

# --- Stack Configuration ---
MODEL_NAME = "openai/gpt-oss-120b"  # Experiment 1 Model
MODEL_PROVIDER = "groq"
APP_VERSION = 1.0

RAG_SYSTEM_PROMPT = """You are an assistant for question-answering tasks. 
Use the following pieces of retrieved context to answer the latest question in the conversation. 
If you don't know the answer, just say that you don't know. 
Use three sentences maximum and keep the answer concise.
"""

openai_client = OpenAI(
    base_url="https://api.groq.com/openai/v1",
    api_key=os.environ.get("GROQ_API_KEY")
)

nest_asyncio.apply()
retriever = get_vector_db_retriever()


@traceable(run_type="chain")
def retrieve_documents(question: str):
    return retriever.invoke(question)


@traceable(run_type="chain")
def generate_response(question: str, documents, model: str = MODEL_NAME):
    # Rule #5: Token Diet
    formatted_docs = "\n\n".join(doc.page_content[:600] for doc in documents)
    messages = [
        {"role": "system", "content": RAG_SYSTEM_PROMPT},
        {"role": "user", "content": f"Context: {formatted_docs} \n\n Question: {question}"}
    ]
    return call_openai(messages, model=model)


@traceable(run_type="llm")
def call_openai(messages: List[dict], model: str = MODEL_NAME) -> str:
    return openai_client.chat.completions.create(
        model=model,
        messages=messages,
        max_tokens=150
    )


@traceable(run_type="chain")
def langsmith_rag(question: str, model: str = MODEL_NAME):
    documents = retrieve_documents(question)
    response = generate_response(question, documents, model=model)
    return response.choices[0].message.content

### Experiment

Here is a code snippet that should look similar to what you see from the starter code!

There are a few important components here.

1. We have defined an Evaluator
2. We pipe our dataset examples (dict) to the shape of input that our function `langsmith_rag` takes (str) using a target function

In [3]:
from langsmith import evaluate, Client

client = Client()

# NOTE: Use the exact name of the dataset you created in Lesson 1
dataset_name = "LangSmith RAG Q&A Dataset" 

def is_concise_enough(reference_outputs: dict, outputs: dict) -> dict:
    candidate = outputs.get("output") if outputs else None
    reference = reference_outputs.get("output") if reference_outputs else ""
    
    # If the model failed or returned None, score it 0 instead of crashing
    if not candidate:
        return {"key": "is_concise", "score": 0}

    score = len(candidate) < 1.5 * len(reference)
    return {"key": "is_concise", "score": int(score)}

def target_function(inputs: dict):
    return langsmith_rag(inputs["question"], model="openai/gpt-oss-120b")

# Run Experiment 1
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="groq-gpt-oss-120b"
)

View the evaluation results for experiment: 'groq-gpt-oss-120b-570a6919' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=9d107241-d724-48a1-b1cb-d08bb0736b39

### Modifying your Application

Now, let's change our model to gpt-35-turbo and see how it performs!

Make this change, and then run this code snippet!

In [5]:
def target_function_qwen(inputs: dict):
    return langsmith_rag(inputs["question"], model="qwen/qwen3.8-27b")

evaluate(
    target_function_qwen,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="groq-qwen-27b"
)

View the evaluation results for experiment: 'groq-qwen-27b-811f7cbc' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=f46d3e98-8aad-4f7e-a70c-691454f4e909

### Running over Different pieces of Data

##### Dataset Version

You can execute an experiment on a specific version of a dataset in the sdk by using the `as_of` parameter in `list_examples`

Let's try running on just our initial dataset.

In [6]:
evaluate(
    target_function,
    data=client.list_examples(dataset_name=dataset_name, as_of="Initial Dataset"),   # We use as_of to specify a version
    evaluators=[is_concise_enough],
    experiment_prefix="initial dataset version"
)

View the evaluation results for experiment: 'initial dataset version-b9599e5a' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=add6c356-182c-4830-90b3-289f227508a5

##### Dataset Split

You can run an experiment on a specific split of your dataset, let's try running on the Crucial Examples split.

In [7]:
evaluate(
    target_function,
    data=client.list_examples(dataset_name=dataset_name, splits=["Crucial Examples"]),  # We pass in a list of Splits
    evaluators=[is_concise_enough],
    experiment_prefix="Crucial Examples split"
)

View the evaluation results for experiment: 'Crucial Examples split-24c329c5' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=19d797b1-636f-48d3-b56c-87909dcb89eb

##### Specific Data Points

You can specify individual data points to run an experiment over as well

In [8]:
# Grab the first 2 example IDs dynamically
sample_examples = list(client.list_examples(dataset_name=dataset_name, limit=2))
two_example_ids = [str(ex.id) for ex in sample_examples]

print(f"Testing specifically on IDs: {two_example_ids}")

evaluate(
    target_function,
    data=client.list_examples(
        dataset_name=dataset_name, 
        example_ids=two_example_ids
    ),
    evaluators=[is_concise_enough],
    experiment_prefix="two specific example ids"
)

Testing specifically on IDs: ['0e04b603-0839-4a85-846c-1b9ea5f18cb8', '1f8b6be5-223e-4ef2-8888-dd7ede3c5c16']
View the evaluation results for experiment: 'two specific example ids-0c651f79' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=24d68cab-247b-464a-b236-565d69c1254f

### Other Parameters

##### Repetitions

You can run an experiment several times to make sure you have consistent results

In [ ]:
# Repetitions
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="two repetitions",
    num_repetitions=2
)

View the evaluation results for experiment: 'concurrency-gpt-20b-5c08d417' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=755f9f06-9d4c-4c53-8cb4-8d3d067c68f8

##### Concurrency
You can also kick off concurrent threads of execution to make your experiments finish faster!

In [12]:
evaluate(
    lambda inputs: langsmith_rag(inputs["question"], model="openai/gpt-oss-20b"),
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="concurrency-gpt-20b",
    max_concurrency=2
)

View the evaluation results for experiment: 'concurrency-gpt-20b-9c01431f' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=4562672f-3728-416c-83ca-9a3ae96eae9e

##### Metadata 

You can (and should) add metadata to your experiments, to make them easier to find in the UI

In [13]:

# Metadata
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="metadata added",
    metadata={
        "model_name": "openai/gpt-oss-120b",
        "provider": "groq",
        "env": "testing"
    }
)

View the evaluation results for experiment: 'metadata added-c862555a' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=5bcfa45c-9c57-44d2-b490-249a66a7571e

In [6]:
evaluate(
    target_function_qwen,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="groq-qwen-27b",
    metadata={
        "model_name": "qwen/qwen3.8-27b",
        "provider": "groq",
        "env": "testing"
    }
)

View the evaluation results for experiment: 'groq-qwen-27b-b128954c' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=b7ddecdc-244e-490f-9a6a-d54a4c3445a6

In [7]:
evaluate(
    lambda inputs: langsmith_rag(inputs["question"], model="openai/gpt-oss-20b"),
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="NOTconcurrency-gpt-20b",

)

View the evaluation results for experiment: 'NOTconcurrency-gpt-20b-f5775b3a' at:
https://smith.langchain.com/o/81d0633c-0684-4f49-9565-e453eca174ad/datasets/cb14c20c-b45e-45a1-9701-5558e8a8a945/compare?selectedSessions=c510a6df-0a6c-4bea-8df7-40f5a386ac8e